### ISSUE TITLE
Error when running PIC (quadprog)

### ISSUE THREAD

**Issue by seanyang38** [cshaowang/pic#1]
Hi, first of all, thanks so much for your implementation on PIC and all the partial multi-view clustering methods. 

However, when I am trying to run PIC, I run into the following error:

> Error using quadprog (line 197)
The 'active-set' algorithm has been removed from quadprog. To avoid this error, choose a different algorithm: 'interior-point-convex' or 'trust-region-reflective'

The error is from PIC.p and I don't think I am able to edit the script on my own. Thanks for your help in advance :)

**Comment by cshaowang** [comment]
Hi, I uploaded PIC.m, which you can change to use 'interior-point-convex'. This error is due to Matlab version issue. Any question, please let me know. Thanks.
